{{- if .Values.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-core-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}-core-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-core-deployment
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      initContainers:
      {{- if .Values.images.eventpublishPlugin }}
      - name: event-publish-plugin
        image: {{ .Values.images.eventpublishPlugin }}
        imagePullPolicy: IfNotPresent 
        command: ['/bin/sh', '-c', "cp -r /plugin/* /var/lib/ASUS/rds/eventpublish"]
        volumeMounts:
        - name: eventpublish-plugin-volume
          mountPath: /var/lib/ASUS/rds/eventpublish
        - name: eventpublish-volume
          mountPath: /plugin/config/eventpublishplugin.yaml
          subPath: eventpublishplugin.yaml
      {{- end }}
      containers:
      - name: {{ .Values.app }}-core
        image: {{ .Values.images.rds }}
        imagePullPolicy: IfNotPresent 
        command: ["/RemoteDispatchService", "serve", "-c","/etc/ASUS/remote-dispatch-service.yaml"]
        ports:
        - containerPort: {{ .Values.service.core.grpc.port }}
        - containerPort: {{ .Values.service.core.http.port }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ASUS
        - name: log-volume
          mountPath: /var/log/ASUS
        - name: socket-volume
          mountPath: /run
        - name: eventpublish-plugin-volume
          mountPath: /var/lib/ASUS/rds/eventpublish
        - name: system-volume
          mountPath: /trusted-cloud/normal/site-storage/14735dfa-5553-46cc-b4bd-405e711b223f/rds
        - name: public-volume
          mountPath: /trusted-cloud/normal/storage
        - name: private-volume
          mountPath: /trusted-cloud/sensitivity/storage
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.core.http.port }}
          initialDelaySeconds: 10
          periodSeconds: 15
      - name: debugger
        image: {{ .Values.images.debugger }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ASUS
        - name: socket-volume
          mountPath: /run
        - name: log-volume
          mountPath: /var/log/ASUS
        - name: eventpublish-plugin-volume
          mountPath: /var/lib/ASUS/rds/eventpublish
      {{- if .Values.images.filebeat }}
      - name: filebeat
        image: {{ .Values.images.filebeat }}
        command: ['filebeat', '-e', '-strict.perms=false', '--path.config', "/etc/filebeat"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/ASUS
        - name: filebeat-config
          mountPath: /etc/filebeat/filebeat.yml
          subPath: filebeat.yml
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.app }}-config
      - name: log-volume
        emptyDir: {}
      - name: socket-volume
        emptyDir: {}
      - name: eventpublish-plugin-volume
        emptyDir: {}
      - name: eventpublish-volume
        configMap:
          name: {{ .Values.app }}-eventpublish-config
      - name: system-volume
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-system-pvc
      - name: public-volume
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-public-pvc
      - name: private-volume
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-private-pvc
      {{- if .Values.images.filebeat }}
      - name: filebeat-config
        configMap:
          name: {{ .Values.app }}-filebeat-config
      {{- end}}
{{- end }}
