apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-headless
  labels:
    app: {{ .Values.app }}
    type: service
spec:
  {{- if eq .Values.service.enableNodePort true }}
  type: NodePort
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  clusterIP: None
  selector:
    app: {{ .Values.app }}
  ports:
    - name: {{ .Values.app }}-port
      port: {{ .Values.service.http_rc.port }}
      targetPort: {{ .Values.service.http_rc.port }}
      {{- if eq .Values.service.enableNodePort true }}
      nodePort: {{ .Values.service.ports.http_rc.nodePort }}
      {{- end }}
      protocol: TCP
